<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TarkovRL</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <Compile Remove="IRLWeaponHandling.Systems\ArmsSystem.cs" />
    <Compile Remove="IRLWeaponHandling.Systems\FluidMovementSystem.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\SPT 4.1.5\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\SPT 4.1.5\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\SPT 4.1.5\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\SPT 4.1.5\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\SPT 4.1.5\EscapeFromTarkov_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>..\..\SPT 4.1.5\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\SPT 4.1.5\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>..\..\SPT 4.1.5\EscapeFromTarkov_Data\Managed\Comfort.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>